"""Initial migration.

Revision ID: 465df5ad365a
Revises: b1ecaa8807e7
Create Date: 2022-07-11 10:14:07.719009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465df5ad365a'
down_revision = 'b1ecaa8807e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('num_worker', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_type', sa.String(length=80), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loose',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['input.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('number', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['input.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weighing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('long_thin', sa.Float(), nullable=False),
    sa.Column('long_thick', sa.Float(), nullable=False),
    sa.Column('short_thin', sa.Float(), nullable=False),
    sa.Column('short_thick', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['input.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('working',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['input.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('working')
    op.drop_table('weighing')
    op.drop_table('number')
    op.drop_table('loose')
    op.drop_table('input')
    op.drop_table('task')
    op.drop_table('worker')
    # ### end Alembic commands ###
