"""Initial migration.

Revision ID: b1ecaa8807e7
Revises: 
Create Date: 2022-07-11 10:03:04.675385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ecaa8807e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weighing')
    op.drop_table('working')
    op.drop_table('input')
    op.drop_table('loose')
    op.drop_table('task')
    op.drop_table('worker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('num_worker', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=80), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loose',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['input.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('input',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('input_type', sa.VARCHAR(length=80), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('working',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hours', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['input.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weighing',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=80), nullable=False),
    sa.Column('long_thin', sa.FLOAT(), nullable=False),
    sa.Column('long_thick', sa.FLOAT(), nullable=False),
    sa.Column('short_thin', sa.FLOAT(), nullable=False),
    sa.Column('short_thick', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['input.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
